import Link from 'next/link'
import './globals.css'
import { Control } from './Control';

export const metadata = {
  title: 'Wep tutorials',
  description: 'Generated by Woodong',
}

export default async function RootLayout({ children }) {
    // const res = await fetch('http://localhost:9999/topics', {next: {revalidate:0}});
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});
    const topics = await res.json();
  return (
    <html>
      <body>
        <h1><Link href='/'>WElCOME</Link></h1>
        <ol>
          {topics.map((topic)=> {
            return<li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control/>
      </body>
    </html>
  )
}
